apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkatwin
  labels:
    app: kafkatwin
    component: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafkatwin
  template:
    metadata:
      labels:
        app: kafkatwin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: kafkatwin
      containers:
      - name: proxy
        image: kafkatwin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: kafka
          containerPort: 9092
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: admin
          containerPort: 8000
          protocol: TCP
        env:
        - name: PROXY_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: PROXY_PORT
          value: "9092"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health/live
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: health
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: kafkatwin-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafkatwin
  labels:
    app: kafkatwin
spec:
  type: ClusterIP
  selector:
    app: kafkatwin
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
    protocol: TCP
  - name: health
    port: 8080
    targetPort: health
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  - name: admin
    port: 8000
    targetPort: admin
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafkatwin
  labels:
    app: kafkatwin
